---
image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"

build:
  stage: build
  script:
    - make rootfs
    - make PLUGIN_TAG=latest create
    - make PLUGIN_TAG=$CI_COMMIT_SHORT_SHA create
    - docker plugin push "$DOCKER_HUB_IMAGE:latest"
    - docker plugin push "$DOCKER_HUB_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - master
