---
image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"

build:
  stage: build
  script:
    - docker build -q -t "${DOCKER_HUB_IMAGE}:rootfs" .
    - mkdir -p ./plugin/rootfs
    - docker create --name tmp "${DOCKER_HUB_IMAGE}:rootfs"
    - docker export tmp | tar -x -C ./plugin/rootfs
    - cp config.json ./plugin/
    - docker rm -vf tmp
    - docker plugin create "${DOCKER_HUB_IMAGE}:latest" ./plugin
    - docker plugin create "${DOCKER_HUB_IMAGE}:${CI_COMMIT_SHORT_SHA}" ./plugin
    - docker plugin push "$DOCKER_HUB_IMAGE:latest"
    - docker plugin push "$DOCKER_HUB_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - master
